export const VERSION_CATALOG = Object.freeze({
  app: { id: "app", name: "HoloMotion Lab DS", version: "4.3.0", type: "Aplicação", status: "estável", summary: "Plataforma holográfica com jogos corporais, biblioteca educacional 3D, aplicativos VR e treinamento experimental do alfabeto manual.", changes: ["Libras Lab ampliado para A–Z.", "Novos modos desafio, sequência e soletração de palavras.", "Feedback por dedo, orientação, contato e movimento.", "Preferência de mão, níveis de precisão e confirmação do professor."] },
  interface: { id: "interface", name: "Interface holográfica", version: "4.3.0", type: "Sistema", status: "estável", summary: "HUD responsivo, navegação horizontal, painéis recolhíveis e diagnóstico detalhado sem ocupar a área central.", changes: ["Painel de dedos e critérios do Libras Lab.", "Controles compactos para palavra, mão e precisão.", "Feedback reduzido no mobile."] },
  vision: { id: "vision", name: "Vision Core", version: "4.3.0", type: "Sensor", status: "estável", summary: "Scheduler adaptativo para mãos, corpo e rosto com processamento local e análise temporal de movimentos.", changes: ["Perfil de alta frequência para datilologia.", "Trajetória do indicador e do dedo mínimo para letras dinâmicas.", "Métricas adicionais de contato e cruzamento dos dedos."] },
  hands: { id: "hands", name: "Hand Tracking", version: "2.7.0", type: "Sensor", status: "estável", summary: "Rastreamento de 21 pontos com orientação, curvatura, contatos entre dedos e trajetórias temporais.", changes: ["Detecção aproximada de contatos do polegar.", "Cruzamento e dobra do indicador.", "Trajetórias experimentais para J e Z."] },
  poseSensor: { id: "poseSensor", name: "Pose Tracking", version: "3.1.0", type: "Sensor", status: "estável", summary: "Esqueleto corporal com 33 pontos, ações corporais, eventos temporais e suporte a uma ou duas pessoas.", changes: ["Detecção de braços abertos, mãos ao alto, agachamento e inclinação.", "Detecção temporal experimental de pulo e palmas."] },
  faceSensor: { id: "faceSensor", name: "Face Tracking", version: "2.0.0", type: "Sensor", status: "experimental", summary: "Mapeamento facial detalhado com olhos, boca, sorriso, sobrancelhas e orientação aproximada da cabeça.", changes: ["Estimativas de inclinação, giro horizontal e vertical.", "Leitura facial mais detalhada e tolerante."] },
  avatar: { id: "avatar", name: "Avatar Holográfico", version: "1.0.0", type: "Sistema", status: "beta", summary: "Representação corporal holográfica que acompanha o esqueleto reconhecido em tempo real.", changes: ["Silhueta robótica sobre o esqueleto.", "Modo híbrido com articulações e corpo virtual."] },
  explorer: { id: "explorer", name: "Holo Explorer", version: "1.0.0", type: "Laboratório", status: "estável", summary: "Biblioteca educacional de hologramas procedurais com espaço, Terra, tecnologia e monumentos.", changes: ["Nove exposições interativas.", "Vista explodida e animações específicas.", "Gestos de pinça, rotação, zoom e troca por deslize." ] },
  sandbox: { id: "sandbox", name: "Holo Sandbox", version: "2.2.0", type: "Laboratório", status: "estável", summary: "Manipulação de objetos 3D por pinça, punho, rotação e duas mãos.", changes: ["Integração visual com o novo núcleo.", "Comandos dinâmicos preservados."] },
  catch: { id: "catch", name: "Shape Catch", version: "2.3.0", type: "Laboratório", status: "estável", summary: "Jogo de coleta corporal com formas, combos e modo para duas pessoas.", changes: ["Telemetria corporal compartilhada com os novos jogos.", "Melhor consistência no modo corpo inteiro."] },
  draw: { id: "draw", name: "Holo Draw", version: "1.5.0", type: "Laboratório", status: "estável", summary: "Desenho no ar com pinça, borracha por punho e exportação em PNG.", changes: ["Integração com o novo perfil de mãos.", "Interface contextual revisada."] },
  pose: { id: "pose", name: "Pose Mirror", version: "1.4.0", type: "Laboratório", status: "estável", summary: "Comparação de poses por ângulos corporais e sustentação temporal.", changes: ["Avatar holográfico opcional.", "Análise corporal compartilhada com a academia."] },
  gestures: { id: "gestures", name: "Gesture Lab", version: "1.4.0", type: "Laboratório", status: "estável", summary: "Treinamento guiado de gestos estáticos, orientação e movimentos rápidos.", changes: ["Novos desafios de negativo, OK e palma frontal.", "Novos movimentos verticais e rotação do punho."] },
  academy: { id: "academy", name: "Academia de Movimentos", version: "1.0.0", type: "Laboratório", status: "estável", summary: "Trilha guiada que ensina como a plataforma reconhece mãos, corpo, pulo e palmas.", changes: ["Doze desafios progressivos.", "Pontuação, progresso e confirmação visual."] },
  sequence: { id: "sequence", name: "Sequência Corporal", version: "1.0.0", type: "Laboratório", status: "estável", summary: "Jogo de memória que combina gestos das mãos e movimentos do corpo em sequências crescentes.", changes: ["Rodadas progressivas de dois a oito comandos.", "Feedback de acerto, erro e pontuação."] },
  aura: { id: "aura", name: "Aura Cósmica", version: "1.0.0", type: "Laboratório", status: "beta", summary: "Experiência galáctica em que movimento corporal e gestos carregam uma aura de partículas.", changes: ["Cinco níveis de energia.", "Partículas emitidas pelas mãos e efeitos ao redor do corpo."] },
  body: { id: "body", name: "Body Challenge", version: "1.0.0", type: "Laboratório", status: "estável", summary: "Jogo corporal contra o tempo com comandos de braços, pernas, agachamento, pulo e palmas.", changes: ["Dez comandos corporais progressivos.", "Pontuação por velocidade, combos e tempo de missão."] },
  dance: { id: "dance", name: "Dance Mirror", version: "1.0.0", type: "Laboratório", status: "beta", summary: "Sequências rítmicas de movimentos corporais com batidas visuais e dificuldade progressiva.", changes: ["Quatro coreografias curtas sem músicas protegidas.", "BPM e sequência aumentam progressivamente."] },
  stretch: { id: "stretch", name: "Alongamento Interativo", version: "1.0.0", type: "Laboratório", status: "beta", summary: "Rotina recreativa de alongamentos e equilíbrio com sustentação temporal.", changes: ["Sete posições orientadas.", "Aviso de uso educativo, não médico."] },
  saber: { id: "saber", name: "Sabre de Energia", version: "1.0.0", type: "Laboratório", status: "beta", summary: "Minijogo holográfico em que os braços controlam sabres luminosos para cortar alvos.", changes: ["Dois sabres associados aos antebraços.", "Alvos, colisões, combo e efeitos energéticos."] },
  libras: { id: "libras", name: "Libras Lab", version: "0.3.0", type: "Laboratório", status: "experimental", summary: "Treinador introdutório do alfabeto manual com A–Z, soletração e feedback geométrico da mão.", changes: ["Alfabeto A–Z com validação aproximada.", "Modos aprender, desafio, sequência e palavra.", "Mão direita, esquerda ou automática.", "Feedback por dedo e confirmação manual para sinais ambíguos."] },
  face: { id: "face", name: "Face Reactor", version: "2.0.0", type: "Laboratório", status: "experimental", summary: "Reator holográfico controlado por sorriso, boca, piscadas e orientação aproximada da cabeça.", changes: ["Análise facial revisada.", "Novos indicadores de direção da cabeça e olhar aproximado."] },
  appStore: { id: "appStore", name: "Aplicativos VR", version: "1.4.0", type: "Sistema", status: "estável", summary: "Catálogo leve de ferramentas Web e aplicativos Android offline com download local.", changes: ["Descrição e versão do Libras Lab atualizadas.", "Filtros e distribuição Android preservados."] },
  pwa: { id: "pwa", name: "PWA e cache", version: "4.3.0", type: "Sistema", status: "estável", summary: "Instalação, cache versionado e atualização segura no GitHub Pages.", changes: ["Cache separado para a versão 4.3.0.", "Libras Lab ampliado incluído no app shell."] }
});

export const MODE_VERSION_KEYS = Object.freeze({ explorer: "explorer", sandbox: "sandbox", catch: "catch", draw: "draw", pose: "pose", gestures: "gestures", academy: "academy", sequence: "sequence", aura: "aura", body: "body", dance: "dance", stretch: "stretch", saber: "saber", libras: "libras", face: "face" });
export const SENSOR_VERSION_KEYS = Object.freeze({ vision: "vision", hands: "hands", pose: "poseSensor", face: "faceSensor" });
export const TECHNOLOGY_CATALOG = Object.freeze([
  { name: "Three.js", version: "0.185.1", role: "Renderização WebGL e objetos 3D", license: "MIT" },
  { name: "MediaPipe Tasks Vision", version: "0.10.35", role: "Rastreamento de mãos, corpo e rosto", license: "Apache-2.0" },
  { name: "Canvas 2D", version: "API do navegador", role: "Aura, avatar, jogos e sobreposições", license: "Padrão Web" },
  { name: "Web Workers", version: "API do navegador", role: "Processamento paralelo da visão", license: "Padrão Web" },
  { name: "IndexedDB / LocalStorage", version: "API do navegador", role: "Preferências e recordes locais", license: "Padrão Web" },
  { name: "Service Worker / Cache Storage", version: "API do navegador", role: "PWA, cache e atualização", license: "Padrão Web" }
]);
export const RELEASE_HISTORY = Object.freeze([
  { version: "4.3.0", date: "2026-07-30", title: "Libras Lab ampliado e soletração experimental", items: ["Alfabeto manual A–Z com validação geométrica aproximada.", "Modos aprender, desafio aleatório, sequência e palavra.", "Feedback por dedo, orientação, curvatura, contato e movimento.", "Preferência de mão, três níveis de precisão e confirmação do professor."] },
  { version: "4.2.0", date: "2026-07-30", title: "Hologramas educacionais e exploração 3D", items: ["Holo Explorer com nove exposições procedurais.", "Sistema Solar, Terra e Lua, hardware, drone, robô, vulcão, caverna, mapa e monumentos.", "Vista explodida, animações e manipulação por gestos.", "Carregamento sob demanda sem backend e sem modelos externos obrigatórios."] },
  { version: "4.1.0", date: "2026-07-30", title: "Desafios corporais, dança, alongamento, sabre e Libras Beta", items: ["Body Challenge com comandos rápidos, tempo, combos e pontuação.", "Dance Mirror e Alongamento Interativo com sequências guiadas.", "Sabre de Energia controlado pelo movimento dos braços.", "Libras Lab experimental com oito configurações iniciais do alfabeto manual."] },
  { version: "4.0.0", date: "2026-07-30", title: "Academia corporal, sequência e aura holográfica", items: ["Academia de Movimentos com treinamento progressivo de mãos e corpo.", "Sequência Corporal com memória, rodadas e comandos mistos.", "Aura Cósmica com partículas reativas, energia e progressão.", "Reconhecimento facial e avatar holográfico revisados."] },
  { version: "3.2.0", date: "2026-07-30", title: "Loja de aplicativos VR e distribuição Android", items: ["Nova aba para experiências Web e aplicativos Android offline.", "APK Lab Virtual DS VR 360 v0.3.3 integrado com download, requisitos e checksum.", "Filtros por plataforma e categorias sem ocupar a área principal do laboratório."] },
  { version: "3.1.0", date: "2026-07-30", title: "Versionamento modular e informações da aplicação", items: ["Catálogo único para versões da aplicação, sensores, laboratórios e tecnologias.", "Badges discretos, painel de detalhes, créditos e resumos curtos de atualização.", "Melhor adaptação das informações técnicas para telas pequenas."] },
  { version: "3.0.0", date: "2026-07-29", title: "Reconstrução do motor e da experiência", items: ["Scheduler adaptativo para mãos, corpo e rosto.", "Gesture Lab, Face Reactor e Shape Catch para duas pessoas.", "Interface responsiva com HUD compacto e painéis recolhíveis."] },
  { version: "2.0.0", date: "2026-07-29", title: "Correções de rastreamento e desempenho", items: ["Alternância das tarefas de visão e classificação geométrica local.", "Correção do espelhamento e das colisões do Shape Catch.", "Perfis de qualidade e clique por gesto."] }
]);
export const PROJECT_CREDITS = Object.freeze({
  project: "HoloMotion Lab DS",
  purpose: "Laboratório educacional de visão computacional, movimento corporal e interação 3D executado integralmente no navegador.",
  direction: "Concepção pedagógica e direção do projeto: Gabriel.",
  engineering: "Arquitetura, interface, lógica de interação e documentação desenvolvidas para o projeto educacional ANALISES.",
  privacy: "A câmera é processada localmente. O projeto não grava nem envia vídeo, áudio, fotos ou localização.",
  licenses: "As dependências de terceiros mantêm suas respectivas licenças. Consulte os projetos oficiais antes de redistribuir versões modificadas."
});
export function getVersionEntry(key) { return VERSION_CATALOG[key] || null; }
export function getModeVersion(mode) { const key = MODE_VERSION_KEYS[mode]; return key ? getVersionEntry(key) : null; }
export function compactVersion(version) { const parts = String(version || "0.0.0").split("."); return `v${parts.slice(0, 2).join(".")}`; }
export function fullVersion(version) { return `v${version || "0.0.0"}`; }
export function entriesByType(type) { return Object.values(VERSION_CATALOG).filter((entry) => entry.type === type); }
