export const VERSION_CATALOG = Object.freeze({
  app: { id: "app", name: "HoloMotion Lab DS", version: "4.5.2", type: "Aplicação", status: "estável", summary: "Visual Upgrade com Holo Blocks, materiais reativos, novos temas de avatar e efeitos gráficos adaptativos.", changes: ["Holo Blocks com 12 materiais, construção, remoção, inspeção e reações.", "Temas visuais Neon, Cósmico, Matriz, Âmbar e Minimalista.", "Avatares Holograma, Robô, Cósmico e Armadura.", "Partículas, materiais e animações adaptadas automaticamente ao perfil de desempenho."] },
  interface: { id: "interface", name: "Interface holográfica", version: "4.5.2", type: "Sistema", status: "estável", summary: "HUD responsivo com painel lateral de reconhecimento e checklist compacto sem bloquear a área central.", changes: ["Ícone dinâmico e instrução correta para cada gesto.", "Confiança, forma, estabilidade e alternativa exibidas separadamente.", "Painel lateral recolhido automaticamente no mobile."] },
  vision: { id: "vision", name: "Vision Core", version: "4.5.1", type: "Sensor", status: "estável", summary: "Scheduler adaptativo com análise de confiança, margem entre candidatos e estabilização por gesto.", changes: ["Classificação usa pontuações concorrentes em vez de uma cadeia rígida.", "Gestos ambíguos exigem confiança mínima antes da estabilização.", "Alternativas próximas são disponibilizadas para diagnóstico."] },
  hands: { id: "hands", name: "Hand Tracking", version: "3.0.0", type: "Sensor", status: "estável", summary: "Rastreamento de 21 pontos com classificação por candidatos, confiança, orientação, curvatura e trajetórias temporais.", changes: ["Positivo e negativo são avaliados antes do punho fechado.", "Margem entre o melhor e o segundo gesto reduz falsos positivos.", "Checklist por dedo e direção do polegar disponível para a interface."] },
  poseSensor: { id: "poseSensor", name: "Pose Tracking", version: "3.1.0", type: "Sensor", status: "estável", summary: "Esqueleto corporal com 33 pontos, ações corporais, eventos temporais e suporte a uma ou duas pessoas.", changes: ["Detecção de braços abertos, mãos ao alto, agachamento e inclinação.", "Detecção temporal experimental de pulo e palmas."] },
  faceSensor: { id: "faceSensor", name: "Face Tracking", version: "2.0.0", type: "Sensor", status: "experimental", summary: "Mapeamento facial detalhado com olhos, boca, sorriso, sobrancelhas e orientação aproximada da cabeça.", changes: ["Estimativas de inclinação, giro horizontal e vertical.", "Leitura facial mais detalhada e tolerante."] },
  objectSensor: { id: "objectSensor", name: "Object Detection", version: "1.0.0", type: "Sensor", status: "beta", summary: "Detecção local de objetos comuns com caixas, categorias, confiança e rastreamento temporal leve.", changes: ["EfficientDet Lite0 carregado somente no Vision Scanner.", "Análise de cores e formas executada no próprio dispositivo.", "Contagem aproximada de pessoas e associação entre mãos e objetos."] },
  explorer: { id: "explorer", name: "Holo Explorer Advanced", version: "2.0.0", type: "Laboratório", status: "estável", summary: "Biblioteca educacional com exploração livre, visita guiada, desafios, quiz e seleção de componentes no holograma.", changes: ["Nove exposições com atividades específicas.", "Partes selecionáveis por clique ou pinça e foco visual.", "Orbit Master, Hardware Repair, Robot Trainer, Volcano Lab e Holo Quiz." ] },
  assembly: { id: "assembly", name: "Holo Assembly", version: "1.1.0", type: "Laboratório", status: "beta", summary: "Montagem por pinça, toque ou mouse com oito kits, tutorial animado e profundidade estimada.", changes: ["Novos kits de rede, satélite, rover e circuito eletrônico.", "Modos de profundidade desligado, assistido e espacial.", "Tutorial animado com mão fantasma e validação prática.", "Formas visuais diferentes para reduzir dependência de cor."] },
  depth: { id: "depth", name: "Depth Trainer", version: "1.0.0", type: "Laboratório", status: "beta", summary: "Treinamento de distância da mão em zonas LONGE, MÉDIO e PERTO usando escala aparente e coordenadas estimadas.", changes: ["Calibração automática de profundidade.", "Jogo de permanência por zonas com combo, pontuação e XP.", "Renderização Canvas 2D carregada sob demanda."] },
  tutorial: { id: "tutorial", name: "Tutorial Animado", version: "1.0.0", type: "Sistema", status: "estável", summary: "Diretor reutilizável de tutoriais com demonstração, validação, repetição e navegação por etapas.", changes: ["Mão fantasma animada.", "Checklist contextual e sustentação temporal.", "Compatibilidade com movimento reduzido."] },
  accessibility: { id: "accessibility", name: "Acessibilidade", version: "1.0.0", type: "Sistema", status: "estável", summary: "Perfis de alto contraste, textos maiores, movimento reduzido e assistência por formas e rótulos.", changes: ["Presets Padrão, Sala, Alto contraste, Texto grande e Movimento reduzido.", "Anúncios ARIA e preferência salva localmente.", "Peças diferenciadas por forma além da cor."] },
  blocks: { id: "blocks", name: "Holo Blocks", version: "1.0.0", type: "Laboratório", status: "beta", summary: "Construção voxel holográfica com terra, água, lava, gelo, lama, cristal, metal, madeira e reações educativas.", changes: ["Doze materiais com propriedades visuais próprias.", "Ferramentas construir, remover e inspecionar.", "Reações água + lava, terra + água, gelo + lava e areia + lava.", "Pinça, toque, mouse, duas mãos e zoom por roda."] },
  visualEngine: { id: "visualEngine", name: "Visual Effects Engine", version: "1.0.0", type: "Sistema", status: "estável", summary: "Temas visuais e materiais adaptativos vinculados aos perfis de desempenho.", changes: ["Cinco temas gráficos.", "Efeitos simplificados automaticamente em FPS baixo.", "Materiais animados de água, lava, gelo e cristal."] },
  avatar: { id: "avatar", name: "Avatar Holográfico", version: "1.2.0", type: "Sistema", status: "beta", summary: "Avatar corporal com estilos Holograma, Robô, Cósmico e Armadura, núcleo energético e rastros adaptativos.", changes: ["Quatro estilos visuais selecionáveis.", "Placas corporais nos modos Robô e Armadura.", "Partículas orbitais no modo Cósmico.", "Rastros reduzidos conforme o perfil gráfico."] },
  sandbox: { id: "sandbox", name: "Holo Sandbox", version: "2.2.0", type: "Laboratório", status: "estável", summary: "Manipulação de objetos 3D por pinça, punho, rotação e duas mãos.", changes: ["Integração visual com o novo núcleo.", "Comandos dinâmicos preservados."] },
  catch: { id: "catch", name: "Shape Catch", version: "2.3.0", type: "Laboratório", status: "estável", summary: "Jogo de coleta corporal com formas, combos e modo para duas pessoas.", changes: ["Telemetria corporal compartilhada com os novos jogos.", "Melhor consistência no modo corpo inteiro."] },
  draw: { id: "draw", name: "Holo Draw", version: "1.5.0", type: "Laboratório", status: "estável", summary: "Desenho no ar com pinça, borracha por punho e exportação em PNG.", changes: ["Integração com o novo perfil de mãos.", "Interface contextual revisada."] },
  pose: { id: "pose", name: "Pose Mirror", version: "1.4.0", type: "Laboratório", status: "estável", summary: "Comparação de poses por ângulos corporais e sustentação temporal.", changes: ["Avatar holográfico opcional.", "Análise corporal compartilhada com a academia."] },
  gestures: { id: "gestures", name: "Gesture Lab", version: "2.0.0", type: "Laboratório", status: "estável", summary: "Treinamento guiado com 16 comandos, checklist por dedo, confiança e diagnóstico de alternativas.", changes: ["Ícone correto para cada desafio.", "Confiança mínima específica por gesto.", "Empurrar e puxar incluídos.", "Pontuação recebe bônus de precisão."] },
  academy: { id: "academy", name: "Academia de Movimentos", version: "1.1.0", type: "Laboratório", status: "estável", summary: "Trilha guiada ampliada com 20 etapas de mãos, orientação, corpo, equilíbrio, pulo e palmas.", changes: ["Novos gestos OK, vitória, rotação e orientação.", "Braços cruzados, defesa e equilíbrio incluídos.", "Instruções e pictogramas centralizados no catálogo de gestos."] },
  sequence: { id: "sequence", name: "Sequência Corporal", version: "1.0.0", type: "Laboratório", status: "estável", summary: "Jogo de memória que combina gestos das mãos e movimentos do corpo em sequências crescentes.", changes: ["Rodadas progressivas de dois a oito comandos.", "Feedback de acerto, erro e pontuação."] },
  aura: { id: "aura", name: "Aura Cósmica", version: "1.0.0", type: "Laboratório", status: "beta", summary: "Experiência galáctica em que movimento corporal e gestos carregam uma aura de partículas.", changes: ["Cinco níveis de energia.", "Partículas emitidas pelas mãos e efeitos ao redor do corpo."] },
  body: { id: "body", name: "Body Challenge", version: "1.0.0", type: "Laboratório", status: "estável", summary: "Jogo corporal contra o tempo com comandos de braços, pernas, agachamento, pulo e palmas.", changes: ["Dez comandos corporais progressivos.", "Pontuação por velocidade, combos e tempo de missão."] },
  dance: { id: "dance", name: "Dance Mirror", version: "1.1.0", type: "Laboratório", status: "beta", summary: "Seis coreografias progressivas com braços, pernas, defesa, agachamento, pulo e precisão de ritmo.", changes: ["Treze movimentos corporais disponíveis.", "Pontuação considera tempo e sustentação.", "BPM progride até 112."] },
  stretch: { id: "stretch", name: "Alongamento Interativo", version: "1.0.0", type: "Laboratório", status: "beta", summary: "Rotina recreativa de alongamentos e equilíbrio com sustentação temporal.", changes: ["Sete posições orientadas.", "Aviso de uso educativo, não médico."] },
  saber: { id: "saber", name: "Sabre de Energia", version: "1.0.0", type: "Laboratório", status: "beta", summary: "Minijogo holográfico em que os braços controlam sabres luminosos para cortar alvos.", changes: ["Dois sabres associados aos antebraços.", "Alvos, colisões, combo e efeitos energéticos."] },
  libras: { id: "libras", name: "Libras Lab", version: "0.3.0", type: "Laboratório", status: "experimental", summary: "Treinador introdutório do alfabeto manual com A–Z, soletração e feedback geométrico da mão.", changes: ["Alfabeto A–Z com validação aproximada.", "Modos aprender, desafio, sequência e palavra.", "Mão direita, esquerda ou automática.", "Feedback por dedo e confirmação manual para sinais ambíguos."] },
  scanner: { id: "scanner", name: "Vision Scanner", version: "1.0.0", type: "Laboratório", status: "beta", summary: "Scanner do ambiente com objetos, pessoas, cores, formas, relações e ações corporais.", changes: ["Scanner livre e cinco experiências orientadas.", "Object Quest, Color Quest, Shape Scanner, Classroom Scanner e Action Detective.", "Reconhecimento provável de objeto segurado, abraço e aperto de mãos."] },
  face: { id: "face", name: "Face Reactor", version: "2.0.0", type: "Laboratório", status: "experimental", summary: "Reator holográfico controlado por sorriso, boca, piscadas e orientação aproximada da cabeça.", changes: ["Análise facial revisada.", "Novos indicadores de direção da cabeça e olhar aproximado."] },
  checklist: { id: "checklist", name: "Motion Checklist", version: "1.0.0", type: "Laboratório", status: "estável", summary: "Tutorial prático com checklist por requisito, sustentação temporal, pontuação e XP.", changes: ["Vinte movimentos guiados.", "Validação separada de mão, dedos, corpo e rosto.", "Navegação manual e progresso persistente."] },
  simon: { id: "simon", name: "Simon Motion", version: "1.0.0", type: "Laboratório", status: "estável", summary: "Jogo de memória corporal com sequências crescentes de gestos e movimentos.", changes: ["Sequências carregadas dinamicamente.", "Rodadas progressivas e XP por conclusão."] },
  reflex: { id: "reflex", name: "Reflex Challenge", version: "1.0.0", type: "Laboratório", status: "estável", summary: "Desafio rápido de comandos com bônus por tempo de resposta e combos.", changes: ["Cronômetro de 45 segundos.", "Medição de resposta e pontuação por velocidade."] },
  marathon: { id: "marathon", name: "Gesture Marathon", version: "1.0.0", type: "Laboratório", status: "beta", summary: "Maratona de movimentos com energia, combos e duração ampliada.", changes: ["Medidor de energia.", "Recuperação por acertos e penalidade por demora."] },
  defender: { id: "defender", name: "Holo Defender", version: "1.0.0", type: "Laboratório", status: "beta", summary: "Jogo defensivo com escudos nas palmas, disparos por punho e escudo corporal.", changes: ["Alvos energéticos em Canvas 2D.", "Defesa com uma ou duas mãos."] },
  hardware: { id: "hardware", name: "Hardware Intelligence", version: "1.0.0", type: "Sistema", status: "estável", summary: "Diagnóstico local de CPU lógica, memória exposta, GPU ativa, WebGL, WebGPU, armazenamento, mídia e sensores físicos.", changes: ["Seleção de múltiplas câmeras e microfones.", "Saída de áudio configurável quando o navegador oferece setSinkId.", "Detecção de acelerômetro, giroscópio, orientação, proximidade e luz ambiente."] },
  benchmark: { id: "benchmark", name: "HoloMotion Benchmark", version: "1.0.0", type: "Sistema", status: "estável", summary: "Teste local de CPU, Canvas 2D, WebGL, memória e taxa de atualização da tela.", changes: ["Pontuação de 0 a 100.", "Perfil e alvo de FPS recomendados.", "Resultado pode ser salvo somente neste dispositivo."] },
  performance: { id: "performance", name: "Performance Manager", version: "2.0.0", type: "Sistema", status: "estável", summary: "Gerenciador adaptativo de FPS, qualidade, sensores, taxa da tela e capacidade real do dispositivo.", changes: ["Perfis DS Ultra e Experimental 240.", "Meta limitada automaticamente pela frequência medida da tela.", "Integração com benchmark e diagnóstico de hardware."] },
  progression: { id: "progression", name: "XP e Progressão", version: "1.0.0", type: "Sistema", status: "estável", summary: "Progressão local com XP, sete níveis, recordes por módulo e conquistas.", changes: ["XP salvo localmente.", "Indicador compacto no topo.", "Animações de nível e recompensa."] },
  moduleLoader: { id: "moduleLoader", name: "Carregamento Modular", version: "1.3.0", type: "Sistema", status: "estável", summary: "Importação dinâmica, pausa e descarregamento dos novos laboratórios.", changes: ["Portal inicial sem motor pesado.", "Módulos carregados somente quando solicitados.", "Liberação manual de memória."] },
  appStore: { id: "appStore", name: "Aplicativos VR", version: "1.5.0", type: "Sistema", status: "estável", summary: "Catálogo leve de ferramentas Web e aplicativos Android offline com download local.", changes: ["Descrição e versão do Libras Lab atualizadas.", "Filtros e distribuição Android preservados."] },
  calibration: { id: "calibration", name: "Calibração Adaptativa", version: "1.0.0", type: "Sistema", status: "beta", summary: "Analisa separação da pinça, tremor, confiança e perdas para sugerir sensibilidade personalizada.", changes: ["Ajuste automático opcional.", "Índice de estabilidade e diagnóstico local.", "Nenhuma imagem ou biometria armazenada."] },
  pwa: { id: "pwa", name: "PWA e cache", version: "4.5.2", type: "Sistema", status: "estável", summary: "Instalação, cache essencial reduzido e atualização segura dos módulos de reconhecimento.", changes: ["Cache essencial da versão 4.5.2.", "Gesture Catalog e motor de confiança são armazenados somente após o runtime ser iniciado."] }
});

export const MODE_VERSION_KEYS = Object.freeze({ blocks: "blocks", explorer: "explorer", assembly: "assembly", depth: "depth", sandbox: "sandbox", catch: "catch", draw: "draw", pose: "pose", gestures: "gestures", academy: "academy", sequence: "sequence", aura: "aura", body: "body", dance: "dance", stretch: "stretch", saber: "saber", libras: "libras", checklist: "checklist", simon: "simon", reflex: "reflex", marathon: "marathon", defender: "defender", scanner: "scanner", face: "face" });
export const SENSOR_VERSION_KEYS = Object.freeze({ vision: "vision", hands: "hands", pose: "poseSensor", face: "faceSensor", objects: "objectSensor" });
export const TECHNOLOGY_CATALOG = Object.freeze([
  { name: "Three.js", version: "0.185.1", role: "Renderização WebGL e objetos 3D", license: "MIT" },
  { name: "MediaPipe Tasks Vision", version: "0.10.35", role: "Rastreamento de mãos, corpo e rosto", license: "Apache-2.0" },
  { name: "EfficientDet Lite0", version: "float16/1", role: "Detecção geral de objetos no Vision Scanner", license: "Apache-2.0 / modelo MediaPipe" },
  { name: "Canvas 2D", version: "API do navegador", role: "Aura, avatar, jogos e sobreposições", license: "Padrão Web" },
  { name: "Web Workers", version: "API do navegador", role: "Processamento paralelo da visão", license: "Padrão Web" },
  { name: "IndexedDB / LocalStorage", version: "API do navegador", role: "Preferências e recordes locais", license: "Padrão Web" },
  { name: "Service Worker / Cache Storage", version: "API do navegador", role: "PWA, cache progressivo e atualização", license: "Padrão Web" },
  { name: "Dynamic import()", version: "ES2020", role: "Carregamento sob demanda de laboratórios", license: "Padrão Web" },
  { name: "MediaDevices", version: "API do navegador", role: "Seleção de câmera, microfone e saídas de áudio", license: "Padrão Web" },
  { name: "WebGPU", version: "API experimental", role: "Diagnóstico do adaptador gráfico de alto desempenho", license: "Padrão Web" },
  { name: "Generic Sensor API", version: "API opcional", role: "Acelerômetro, giroscópio, proximidade e luz ambiente", license: "Padrão Web" },
  { name: "PerformanceObserver", version: "API do navegador", role: "Diagnóstico de tarefas longas e desempenho", license: "Padrão Web" }
]);
export const RELEASE_HISTORY = Object.freeze([
  { version: "4.5.2", date: "2026-07-31", title: "Visual Upgrade e Holo Blocks", items: ["Holo Blocks com doze materiais e construção voxel.", "Reações educativas entre água, lava, terra, gelo e areia.", "Temas visuais adaptativos e quatro estilos de avatar.", "Carregamento sob demanda e redução automática de efeitos em FPS baixo."] },
  { version: "4.5.1", date: "2026-07-31", title: "Recognition Upgrade", items: ["Correção da confusão entre positivo e punho fechado.", "Gesture Lab com pictogramas corretos, checklist, confiança e estabilidade.", "Academia ampliada para vinte etapas e Dance Mirror para seis coreografias.", "Avatar holográfico com núcleo energético e rastros adaptativos."] },
  { version: "4.5.0", date: "2026-07-31", title: "Performance Engine e inteligência de hardware", items: ["Central de hardware com seleção de câmera, microfone e saída de áudio.", "Benchmark local de CPU, Canvas, WebGL, memória e frequência da tela.", "GPU ativa, WebGPU, armazenamento, heap JavaScript e sensores físicos no diagnóstico.", "DS Ultra, meta de 120 FPS e modo experimental limitado pela tela real."] },
  { version: "4.4.4", date: "2026-07-31", title: "Profundidade, tutorial animado e acessibilidade", items: ["Holo Assembly ampliado para oito kits com encaixe espacial opcional.", "Depth Trainer para LONGE, MÉDIO e PERTO.", "Tutorial animado com validação etapa por etapa.", "Alto contraste, textos maiores, movimento reduzido e assistência por formas."] },
  { version: "4.4.3", date: "2026-07-31", title: "Holo Assembly, calibração e estabilidade", items: ["Quatro kits de montagem com pinça, mouse e toque.", "Calibração adaptativa de sensibilidade e índice de estabilidade.", "Melhor redução de partículas, pixel ratio e efeitos em quedas de FPS.", "Novos desafios guiados, dicas, pontuação e XP."] },
  { version: "4.4.2", date: "2026-07-31", title: "Holo Explorer Advanced e atividades educacionais", items: ["Exploração livre, visita guiada, desafio e Holo Quiz.", "Partes selecionáveis em nove maquetes procedurais.", "Orbit Master, Hardware Repair, Drone Balance, Robot Trainer, Volcano Lab e Crystal Hunt.", "Pontuação, XP, foco de componentes e simulação vulcânica."] },
  { version: "4.4.1", date: "2026-07-31", title: "Vision Scanner e inteligência do ambiente", items: ["Detector de objetos carregado somente ao abrir o scanner.", "Object Quest, Color Quest, Shape Scanner, Classroom Scanner e Action Detective.", "Contagem aproximada de pessoas, cores, formas e relações entre mãos e objetos.", "Ações temporais e interações prováveis entre duas pessoas."] },
  { version: "4.4.0", date: "2026-07-30", title: "Arquitetura modular, DS Turbo e Motion Academy Pro", items: ["Portal inicial leve com runtime carregado somente ao iniciar.", "Sete perfis de desempenho e modos de uso especializados.", "Motion Checklist, Simon Motion, Reflex Challenge, Gesture Marathon e Holo Defender.", "XP, níveis, animações reativas e descarregamento de módulos inativos."] },
  { version: "4.3.0", date: "2026-07-30", title: "Libras Lab ampliado e soletração experimental", items: ["Alfabeto manual A–Z com validação geométrica aproximada.", "Modos aprender, desafio aleatório, sequência e palavra.", "Feedback por dedo, orientação, curvatura, contato e movimento.", "Preferência de mão, três níveis de precisão e confirmação do professor."] },
  { version: "4.2.0", date: "2026-07-30", title: "Hologramas educacionais e exploração 3D", items: ["Holo Explorer com nove exposições procedurais.", "Sistema Solar, Terra e Lua, hardware, drone, robô, vulcão, caverna, mapa e monumentos.", "Vista explodida, animações e manipulação por gestos.", "Carregamento sob demanda sem backend e sem modelos externos obrigatórios."] },
  { version: "4.1.0", date: "2026-07-30", title: "Desafios corporais, dança, alongamento, sabre e Libras Beta", items: ["Body Challenge com comandos rápidos, tempo, combos e pontuação.", "Dance Mirror e Alongamento Interativo com sequências guiadas.", "Sabre de Energia controlado pelo movimento dos braços.", "Libras Lab experimental com oito configurações iniciais do alfabeto manual."] },
  { version: "4.0.0", date: "2026-07-30", title: "Academia corporal, sequência e aura holográfica", items: ["Academia de Movimentos com treinamento progressivo de mãos e corpo.", "Sequência Corporal com memória, rodadas e comandos mistos.", "Aura Cósmica com partículas reativas, energia e progressão.", "Reconhecimento facial e avatar holográfico revisados."] },
  { version: "3.2.0", date: "2026-07-30", title: "Loja de aplicativos VR e distribuição Android", items: ["Nova aba para experiências Web e aplicativos Android offline.", "APK Lab Virtual DS VR 360 v0.3.3 integrado com download, requisitos e checksum.", "Filtros por plataforma e categorias sem ocupar a área principal do laboratório."] },
  { version: "3.1.0", date: "2026-07-30", title: "Versionamento modular e informações da aplicação", items: ["Catálogo único para versões da aplicação, sensores, laboratórios e tecnologias.", "Badges discretos, painel de detalhes, créditos e resumos curtos de atualização.", "Melhor adaptação das informações técnicas para telas pequenas."] },
  { version: "3.0.0", date: "2026-07-29", title: "Reconstrução do motor e da experiência", items: ["Scheduler adaptativo para mãos, corpo e rosto.", "Gesture Lab, Face Reactor e Shape Catch para duas pessoas.", "Interface responsiva com HUD compacto e painéis recolhíveis."] },
  { version: "2.0.0", date: "2026-07-29", title: "Correções de rastreamento e desempenho", items: ["Alternância das tarefas de visão e classificação geométrica local.", "Correção do espelhamento e das colisões do Shape Catch.", "Perfis de qualidade e clique por gesto."] }
]);
export const PROJECT_CREDITS = Object.freeze({
  project: "HoloMotion Lab DS",
  purpose: "Laboratório educacional de visão computacional, movimento corporal e interação 3D executado integralmente no navegador.",
  direction: "Concepção pedagógica e direção do projeto: Gabriel.",
  engineering: "Arquitetura, interface, lógica de interação e documentação desenvolvidas para o projeto educacional ANALISES.",
  privacy: "A câmera é processada localmente. O projeto não grava nem envia vídeo, áudio, fotos ou localização.",
  licenses: "As dependências de terceiros mantêm suas respectivas licenças. Consulte os projetos oficiais antes de redistribuir versões modificadas."
});
export function getVersionEntry(key) { return VERSION_CATALOG[key] || null; }
export function getModeVersion(mode) { const key = MODE_VERSION_KEYS[mode]; return key ? getVersionEntry(key) : null; }
export function compactVersion(version) { const parts = String(version || "0.0.0").split("."); return `v${parts.slice(0, 2).join(".")}`; }
export function fullVersion(version) { return `v${version || "0.0.0"}`; }
export function entriesByType(type) { return Object.values(VERSION_CATALOG).filter((entry) => entry.type === type); }
